name: Build and Publish Image to Docker Hub
on:
  [workflow_dispatch]
jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4        
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build image
        run: docker build ./ -t lpriemis/dockertest:latest
      - name: push image to docker hub
        run: 
          docker push lpriemis/dockertest:latest
