name: Build and Publish Image to Docker Hub
on:
  [workflow_dispatch]
jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4        
      - name: build image
        run: docker build ./ -t lpriemis/dockertest:latest
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: lpriemis
          password: dckr_pat_2oa-60ivj0S5ZR6EjQnPmbrV9Dg
      - name: push image to docker hub
        run: 
          docker push lpriemis/dockertest:latest
